- src/editor/components/Cell/Content/index.js
- src/editor/components/Editable/blur.js
- src/editor/plugins/content/slate/Component/index.js
- src/editor/plugins/content/slate/index.js
- src/editor/plugins/content/slate/plugins/link/index.js
> plugin/slate: how to add modals for e.g. links - closes #263

- src/editor/actions/cell/core.js
- src/editor/actions/cell/insert.js
- src/editor/actions/helpers.js
- src/editor/plugins/layout/spoiler/index.js
- src/editor/reducer/editable/index.js
Failing tests, see #260. Furthermore, there are still some flow issues left from the plugin refactor.
> 0.0.4 empty cells

- docs/README.md
removed cell 1.1 from content cells list
> docs: correct content cell example

- .travis.yml
see https://blog.travis-ci.com/2016-11-21-travis-ci-now-supports-yarn
> ci: cache .yarn-cache

- examples/home/src/content.js
- src/editor/plugins/content/slate/plugins/lists.js
> plugin/slate: fix lists plugin

- examples/home/src/index.js
- src/editor/actions/index.js
- src/editor/index.js
- src/editor/index.test.js
- src/editor/selector/editable/index.js
- src/editor/service/plugin/index.js
Exposes stuff like:
```jsx
editor.trigger.mode.toggleInsert()
```
> core: expose programmatic api - closes #267

- README.md
I fine tuned the language a little
> Language massaging for the readme

- examples/src/index.js
- packages/core/src/index.js
- packages/core/src/reducer/editable/index.test.js
- packages/core/src/reducer/editables/index.js
- packages/core/src/service/plugin/index.js
- packages/core/src/service/plugin/missing.js
> core: update content when updating plugins

- docs/tutorials.md
As explained in #423, I had trouble figuring this out so thought it'd be nice to have an example.
I tried to stay away from advanced things like class properties and such.  Am happy to rework if you'd prefer any changes or to demonstrate other features.
Thanks for your work on the editor.
> Document saving and restoring editor state

- packages/core/src/grid.css
See https://bugzilla.mozilla.org/show_bug.cgi?id=1391821
> core/grid: resolve firefox grid issue

- packages/plugins/content/slate/package.json
- packages/plugins/content/slate/src/index.js
- packages/plugins/content/slate/yarn.lock
> plugins/slate: add parse5 as parsefunction to enable server side parsing

- .yarnclean
- config/postcss.colors.js
- packages/core/src/components/Cell/Resizable/index.css
> core: mix resize indicator with background for better visibility

- docs/tutorials.md
> Remove unused import.

- packages/plugins/content/image/src/Component/Display/index.js
- packages/plugins/content/image/src/Component/Form/index.js
This allows one to specify a link location URL which would turn the image into a link. Additionally, a checkbox is provided for opening the link in a new window.
Let me know if there is anything you need me to do to get this in.
> Allow images to be links

- packages/plugins/content/slate/src/index.js
> Slate now exports defaultPlugins

- packages/plugins/content/slate/src/helpers.js
- packages/plugins/content/slate/src/index.js
- packages/plugins/content/slate/src/plugins/code/index.js
- packages/plugins/content/slate/src/plugins/link/index.js
- packages/plugins/content/slate/src/plugins/lists.js
@PeterKottas can you please confirm that this has the changes required for lists to be fixed? Thanks!
> plugins/slate: Add list fix lost in merge

- packages/plugins/layout/background/src/index.js
Let me know if I forgot to run any build scripts.
I'm also interested in adding i18n to the project, would that be accepted?
> layout/background: Only render BottomToolbar when we are in edit mode

- docs/README.md
Images not shown in previous version.
> relative path

- docs/api/core.md
- packages/core/src/index.ts
- packages/core/src/reducer/editables/__tests__/index.test.ts
- packages/core/src/reducer/focus/__tests__/index.test.ts
- packages/core/src/reducer/index.ts
- packages/core/src/selector/display/index.ts
- packages/core/src/selector/editable/__tests__/index.test.ts
- packages/core/src/selector/editable/index.ts
- packages/core/src/selector/focus.ts
- packages/core/src/selector/setting.ts
- packages/core/src/types/state.ts
> Change reducer name

- .github/ISSUE_TEMPLATE/bug-report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
> Add issue and PR github template

- packages/core/src/components/Cell/Content/index.tsx
- packages/core/src/components/Cell/Layout/index.tsx
- packages/core/src/components/Cell/index.tsx
- packages/core/src/service/plugin/classes.ts
- packages/plugins/content/html5-video/src/Controls/Html5VideoDefaultControls.tsx
- packages/plugins/content/image/src/Controls/ImageDefaultControls.tsx
- packages/plugins/content/video/src/Controls/VideoDefaultControls.tsx
- packages/plugins/createPluginMaterialUi/src/Controls/index.tsx
- packages/ui/src/BottomToolbar/index.tsx
- packages/ui/src/Trash/index.css
this adds a remove button on most plugin. This is an alternative to the trash drop target and sometimes more easy to use
> feat: add remove button on (most) plugins

- packages/core/tsconfig-es.json
- packages/plugins/content/divider/tsconfig-es.json
- packages/plugins/content/html5-video/tsconfig-es.json
- packages/plugins/content/image/tsconfig-es.json
- packages/plugins/content/native/tsconfig-es.json
- packages/plugins/content/slate/tsconfig-es.json
- packages/plugins/content/spacer/tsconfig-es.json
- packages/plugins/content/video/tsconfig-es.json
- packages/plugins/createPluginMaterialUi/tsconfig-es.json
- packages/plugins/layout/background/tsconfig-es.json
- packages/renderer/tsconfig-es.json
- packages/ui/tsconfig-es.json
> Don't use target es6 in es transpile to support IE11 (#742)

- packages/core/src/components/Cell/Resizable/index.tsx
resizing sometimes did not work, this fixes that.
it does not fix it for inline elements. If an element is inlined right, resizing is still buggy.
> fix: resize

- packages/core/package.json
This updates the version of the dependency.
The older version, uses `this` on the top level of the module, causing failure in strict environments.
In `strict` environment (like a ES6 module), top level this is undefined.
Fixes #
> Update dep element-resize-event

- packages/plugins/content/slate/src/slateEnhancer/withPaste.ts
We should keep data copied from slate editor as-is instead of manipulate it by text/html or plain/text.
> Do not manipulate data copied from slate editor

- package.json
- packages/core/src/Provider/index.tsx
- packages/core/src/actions/cell/insert.ts
- packages/core/src/actions/display.ts
- packages/core/src/components/BlurGate.tsx
- packages/core/yarn.lock
- packages/editor/src/editor/EditableEditor.tsx
- packages/editor/src/editor/index.tsx
Detailed in https://github.com/react-page/react-page/issues/800
> Added props to disable BlurGate

- examples/src/elements.css
- examples/src/styles.css
- package.json
- packages/core/src/components/BlurGate.tsx
- packages/core/src/components/Cell/Draggable/index.css
- packages/core/src/components/Cell/Draggable/index.tsx
- packages/core/src/components/Cell/Layout/index.tsx
- packages/ui/src/BottomToolbar/index.tsx
- packages/ui/src/SelectParentButton/index.tsx
There was a bug in the blur gate. Apparently you cannot return null in useEffect, also a small issue with dependency. @macrozone, could you please release this? Or preferably let me know how to release so that I don't have to bug you about this. Cheers!
> Fixes blur gate and remove docsify dependency

- packages/core/package.json
- packages/ui/package.json
This should temporarily fix the issue with loadable as mentioned in #838
Fixes #838
> Fix the version of @loadable/component to fix #838

- packages/core/src/service/plugin/classes.ts
> doc(plugin): fix a few documentation comments

- packages/editor/src/editor/EditableEditor.tsx
- packages/editor/src/editor/index.tsx
- packages/ui/src/EditorUI/__tests__/__snapshots__/index.test.tsx.snap
- packages/ui/src/EditorUI/__tests__/index.test.tsx
- packages/ui/src/EditorUI/index.tsx
Sometimes you just want a simple editor without so many options, this PR allows you to hide the sidebar menu.
Fixes #836
> Add option to hide the sidebar menu when you need.

- UPGRADE.md
> migration steps from 0 to 1

- packages/plugins/content/spacer/src/Renderer/SpacerHtmlRenderer.tsx
- packages/plugins/content/spacer/src/Renderer/SpacerResizable.tsx
- packages/plugins/content/spacer/src/createPlugin.tsx
- packages/plugins/content/spacer/src/index.css
fix(plugin-spacer): shows border in read only mode
fix(plugin-spacer): spacer has now correct size (without 2 additional pixel from the borde)
the border has been removed and replaced with an outline.
This fixes the problem as well that it was actually 2 pixels taller in height as specified.
this might have a slight inpact on existing page layouts and could be considered a breaking change,
but its too sublte and probably few will notice. Please raise an issue if you notice a problem with that.
Fixes #
> fix(plugin-spacer): resizing is broken

- packages/editor/src/core/components/Cell/PluginComponent/index.tsx
Revert to using display:block type of layout in case of inline cells.
#918
> fix(inline): fix inline layout

- packages/editor/src/renderer/HTMLRenderer.tsx
Fix the issue with inline floats in read-only mode.
#918
> HTMLRenderer inline mode fix

- config/jestTestSetup.js
- package.json
- packages/editor/src/core/Provider/index.tsx
- packages/editor/src/core/components/hooks/__tests__/useDebouncedCellData.test.tsx
- packages/editor/src/core/components/hooks/node.ts
- packages/editor/src/core/reducer/index.ts
- packages/plugins/content/slate/src/components/SlateProvider.tsx
- yarn.lock
Fixed useDebouncedCellData as discussed in #948.
Added 2 unit tests to verify the fixes of two outlined problems + another one ("outside changes") to make sure the original corner case logic works as before.
#948
> bug(hook): useDebouncedCellData fix

- packages/editor/src/core/components/Cell/Draggable/index.tsx
- packages/editor/src/core/components/Cell/Draggable/useDragHandle.tsx
- packages/editor/src/core/components/Cell/Handle/index.css
- packages/editor/src/core/components/Cell/Handle/index.tsx
fixes https://github.com/react-page/react-page/issues/962
- [] I have added necessary documentation (if appropriate)
closes https://github.com/react-page/react-page/issues/962
> fix: switching between resize mode and other modes is slow

- docs/custom-cell-plugins.md
- examples/pages/examples/nestedPlugins.tsx
- packages/editor/src/core/actions/cell/insert.ts
- packages/editor/src/core/components/Cell/Droppable/index.css
- packages/editor/src/core/components/Cell/Droppable/index.tsx
- packages/editor/src/core/components/Cell/InsertNew.tsx
- packages/editor/src/core/components/Cell/PluginComponent/index.tsx
- packages/editor/src/core/components/Cell/index.css
- packages/editor/src/core/components/Cell/index.tsx
- packages/editor/src/core/components/Editable/FallbackDropArea.tsx
- packages/editor/src/core/components/HotKey/Decorator.tsx
- packages/editor/src/core/components/Row/Droppable/index.tsx
- packages/editor/src/core/components/Row/index.tsx
- packages/editor/src/core/components/hooks/__tests__/useDebouncedCellData.test.tsx
- packages/editor/src/core/components/hooks/dragDropActions.ts
- packages/editor/src/core/components/hooks/node.ts
- packages/editor/src/core/components/hooks/nodeActions.ts
- packages/editor/src/core/components/hooks/options.ts
- packages/editor/src/core/migrations/migrate.ts
- packages/editor/src/core/reducer/display/index.ts
- packages/editor/src/core/types/plugins.ts
- packages/editor/src/core/utils/getAvailablePlugins.ts
- packages/editor/src/core/utils/getCellData.ts
- packages/editor/src/renderer/HTMLRenderer.tsx
- packages/editor/src/ui/PluginDrawer/Item/index.tsx
- packages/editor/src/ui/PluginDrawer/index.tsx
- packages/plugins/content/slate/src/index.tsx
fixes https://github.com/react-page/react-page/issues/952
(already available on beta)
> allow to nest plugins (release on master)

- packages/editor/src/core/components/Cell/Draggable/index.tsx
Signed-off-by: Peter Kottas <petokottas@gmail.com>
One more place with stopPropagation.
> Fix: More StopPropagation

- packages/editor/src/core/components/hooks/node.ts
Fix: Fixed error where when dragging selected text (or other things) editor breaks.
> Fix: Error when dragging

- packages/editor/src/core/Provider/useOptionsMemoized.ts
Fix: Added Insert new to default options
> Fix: Added InsertNew to default options (as NULL)

- packages/editor/src/core/components/Cell/InsertNew.tsx
- packages/editor/src/core/components/HotKey/GlobalHotKeys.tsx
- packages/editor/src/editor/EditableEditor.tsx
To Open the Cell Plugins on pressing the slash "/" key
> handle the slash '/' command to open the insert plugin sidebar #982

- config/tsconfig.test.json
- docs/_sidebar.md
- docs/recipes.md
- docs/utils.md
- examples/pages/examples/extractTextContents.tsx
- packages/editor/src/core/types/plugins.ts
- packages/editor/src/core/utils/getTextContents.test.ts
- packages/editor/src/core/utils/getTextContents.ts
- packages/editor/src/index.tsx
- packages/editor/tsconfig.json
- packages/plugins/content/divider/tsconfig.json
- packages/plugins/content/html5-video/tsconfig.json
- packages/plugins/content/image/tsconfig.json
- packages/plugins/content/slate/src/__tests__/getTextContents.test.ts
- packages/plugins/content/slate/src/__tests__/htmlToSlate.test.ts
- packages/plugins/content/slate/src/components/renderHooks.tsx
- packages/plugins/content/slate/src/htmlToSlate/HtmlToSlate.tsx
- packages/plugins/content/slate/src/index.tsx
- packages/plugins/content/slate/src/utils/getTextContent.ts
- packages/plugins/content/slate/tsconfig.json
- packages/plugins/content/spacer/tsconfig.json
- packages/plugins/content/video/tsconfig.json
- packages/plugins/layout/background/tsconfig.json
- packages/react-admin/tsconfig.json
- packages/tsconfig.settings.json
getTextContents can be used to extract plaintext from the editors value
this mr also includes some docs updates
> feat: getTextContents

- docs/editor.md
Fix links to demos in editor documentation.
> Fix links to demos in editor documentation

- package.json
- packages/editor/package.json
- packages/editor/src/core/helper/lazyLoad/index.tsx
- packages/editor/src/ui/AutoformControls/AutoForm.tsx
- yarn.lock
this approach replaces loadable component with a custom one. This one uses Suspense on the frontend and renders the fallback on the backend
fixes https://github.com/react-page/react-page/issues/1227
> fix: react-page not working with vite

- .github/workflows/release.yaml
> chore: fix github token env var for release

- packages/plugins/content/slate/src/components/SlateProvider.tsx
this does not solve it entirly, but mitigatates the problem a lot
the issue stems from the fact that slate became an uncontrolled input which makes it hard to use with outside values
> fix(slate): slate loses some updates / keystrokes
