react-page/react-page

packages/core/src/components/Editable/index.js
Editable component was missing unsubscribing from redux store on component unmounting. This one should fix #404.
=> components/Editable: unsubscribe from redux store

packages/plugins/content/slate/src/Component/index.js
Here is a quick PR modeled after [this example](https://github.com/ianstormtaylor/slate/blob/v0.21.6/examples/paste-html/index.js) to allow HTML pasting.
=> HTML copy-pasting

.travis.yml
`precise` is now considered deprecated
=> run on new trusty travis

packages/core/src/reducer/editable/tree.js, packages/core/src/service/plugin/classes.js
Hello,
I followup a recently added feature request #509 by this PR
My use case is a layout plugin that shares some of its state with other plugins, with some data transformations during synchronization ...
To achieve this, we have created a special HOC that subscribes to ory store, looks for target states based on filter criteria, and maps the results to the current / wrapped plugin. the solution works as expected but it has a performance impact and it is declarative (we prefer it imperative for more control).
By using the option "reducer" of plugin we can achieve the same without the cons of the HOC solution. but unfortunately, the layout plugin does not support it. this PR is about adding "reducer" option support  for the layout plugin .
Please review this PR and consider merging it.
If …
=> plugin: add alternative reducer support for layout plugin

package.json
Following discussion on issue https://github.com/ory/editor/issues/524
Here is a precommit hook to run the docs:api on every commit mail. Then the commiter will see the lerna message and the new unstaged files and can decide to add them in a new commit or not (nothing mandatory so it's simpler).
Another option would be to run the doc generation on origin repo after each change on the master branch but I'm not sure how to do this and I lack access to give it a try.
=> feat(doc): add pre-commit githook to regenerate documentation

package.json
It seems we need babel-preset-react-app to build project but it is not into package.json.
=> Add babel-preset-react-app as project dependency

packages/plugins/content/slate/src/Component/index.js, packages/plugins/content/slate/src/index.js, packages/renderer/src/index.test.js
Currently it is hard to define styles for this container due to no class name. Rather than putting in an issue, thought I would add it. This might have been intentional behaviour / ory user defined behaviour, although I couldn't find any docs for this.
Also I tried to remain consistent with the naming convention I saw, although I'm not 100% certain 'container' is the preferred word in this repo
=> Add ory-plugins-content-slate-container class to outer slate div

packages/plugins/layout/parallax-background/src/index.js, packages/ui/src/Toolbar/index.js
- Parallax bg input fields were not working
- If you didn't provide any content/layout plugins, instead of nothing, it showed "0" literally in the ui as that's the length of plugin array
=> Fixed few issues

packages/core/src/components/HotKey/Decorator.js, packages/core/src/index.js, packages/core/src/reducer/editable/index.test.js, packages/core/src/reducer/editables/index.js, packages/core/src/reducer/editables/index.test.js, packages/core/src/reducer/focus/index.test.js, packages/core/src/reducer/index.js, packages/core/src/selector/display/index.js, packages/core/src/selector/editable/index.js, packages/core/src/selector/editable/index.test.js, packages/core/src/selector/focus.js, packages/core/src/selector/index.js, packages/core/src/selector/setting.js, packages/core/src/types/editable.js, packages/core/src/types/redux.js, packages/core/src/types/state.js, packages/plugins/content/divider/package.json, packages/plugins/content/slate/src/helpers.js, packages/plugins/content/slate/src/index.js, packages/plugins/content/slate/src/plugins/code/index.js, packages/plugins/content/slate/src/plugins/link/index.js, packages/plugins/content/slate/src/plugins/lists.js, packages/plugins/layout/background/src/index.js
See #616 for original conversation
Todos
====
Comments
====
I had some troubles with the tests, as it seems they use the npm packages rather than the local builds and there were a lot of unrelated console errors. The `Contributing.md` docs seem to not be updated for this npm package (`Run the full project test suite with the go test ./... (or equivalent) command and confirm that it passes.`)
Also it seems some files weren't properly `prettified`, so they are updated although I didn't change them.
I also updated some flow types 
Usage
====
```js
// ...
import { oryReducer } from 'ory-editor-core'
const reducer = combineReducers({
// ...
ory: oryReducer 
});
const store = createStore(reducer, null, middleware);
new Editor({ store })
```
=> Adds ability to use with own redux store

packages/plugins/content/html5-video/src/Component/index.js
A few things were broken:
1. the `<TextField>` wasn't changing its value
2. the width was very small (I changed to be the same as in the other `video` plugin)
3. when the value was changed, the html element wasn't updated accordingly (needed a page refresh to show the new content)
=> Bugfixes in html5video

packages/plugins/content/video/src/Renderer/VideoHtmlRenderer.tsx
https://github.com/facebook/react/issues/1881
The video plugin doesn't fill the container currently
=> Remove !important from inline style as unsupported

packages/plugins/content/video/src/Component/index.tsx, packages/plugins/content/video/src/Controls/VideoDefaultControls.tsx
Problems fixed:
- Clicking outside of the `BottomToolbar` now calls the `TextField.onBlur` event. It was not calling because of the `focused` prop, it was unmounting the `BottomToolbar` component, therefor not calling `TextField.onBlur`;
- Save the `this.state.src` in a variable to send it in `this.props.onChange`. It was sending always `undefined`.
=> Fixing wrong state management in video plugin

packages/core/src/components/HotKey/Decorator.tsx
#583 fixed #579 but I'm still receiving those errors on sentry sometimes:
`null is not an object (evaluating 't.props.searchNodeEverywhere(t.props.focus)`
`Cannot read property 'node' of null`
I've seen that they are coming from the focusNext function, I'm simply applying the same fix that was applied to the remove function to the focusNext and focusPrev function.
=> Check if node exists on focusNext and focusPrev

packages/core/src/components/Cell/Layout/index.tsx
I wonder Why this doesn't break the whole package?
=> fix: name is not defined in Cell/Layout

.travis.yml, travis-deploy.sh
The build:lib command is already being executed when running yarn, the second time the command runs we get an error thrown on travis, not sure if it's intentional to run it 3 times when making a release but this should speed up the builds and make travis green.
I've tested in my fork and was able to release a version with this config to npm, I'm using it in production in the past weeks without any issues.
We should be able to change the namespaces and make a new release after this.
=> Remove redundant build:lib steps

packages/plugins/layout/background/src/createPlugin.tsx, packages/plugins/layout/background/src/types/settings.ts, packages/plugins/layout/parallax-background/src/createPlugin.tsx, packages/plugins/layout/parallax-background/src/types/settings.ts
The purpose of this is to allow implementers to override the initial children defaults.
This PR opens up the possibility of having a group of plugins with configurations within each other stored as a plugin which can easily be reused. For example a page section template consisting of layout, an image, spacing and text could be stored as a plugin by the implementer by implementing this override
=> Override layout createinitialchildren

README.md
I replaced ORY Editor with ReactPage and updated the install instruction.
I also removed the `pre-release` warning and the mention that it is a personal project of aeneasr, because it should now be community driven.
We should also update the sub packages, but i wanted to focus on the readme.
Any more changes to do?
=> Update README.md to match the new name

packages/plugins/content/slate/package.json, packages/plugins/content/slate/src/Controls/index.tsx, packages/plugins/content/slate/src/plugins/link/index.tsx, packages/plugins/content/slate/src/serialization/index.tsx
remove parse5 and replace it with jsdom on server and in tests. This reduces the bundle size by around 200kb.
also parse5 is not supported anymore by slate officially, altough it did not seem to have caused problems.
based on my previous refactor https://github.com/react-page/react-page/pull/700
we should merge that and then i will do a rebase here
=> Remove parse5

packages/plugins/content/slate/src/default/settings.ts, packages/plugins/content/slate/src/plugins/link/Controls.tsx, packages/plugins/content/slate/src/plugins/link/LinkButton.tsx, packages/plugins/content/slate/src/plugins/link/index.tsx
slate link plugin now allow to define whether links should open in a new window
I added it while doing a refactor of the link plugin. I later want to allow for more complex plugins, like page links which store a pageId instead of a href and generate the href on render. The slate plugins are still a bit verbose and therefore hard to extend or customize. The goal is to have a similar flexibility like  with `@react-page/create-plugin-materialui`
slate link plugin has a checkbox which defines whether link opens in new window (`target="_blank"`)
Its *a little breaking*, but only if you override `getComponent` of the link plugin, which was a brand-new feature..
- [  I have added tests that prove my fix is effective or that my feature works
=> feat: allow to define whether link should open in new window

packages/plugins/content/slate/src/serialization/index.tsx
Like discussed in https://github.com/react-page/react-page/issues/721 it is neccessary to (un)serialize also other props than editorState of slate to allow wrapping other components arround slate.
=> extended serialize and unserialize functions of slate plugin to handle also other props

docs/plugins/create.md, examples/src/customLayoutPlugin.tsx, examples/src/index.tsx, packages/core/src/helper/createInitialChildren/index.ts, packages/core/src/helper/sanitizeInitialChildren/index.ts, packages/core/src/index.ts, packages/core/src/service/plugin/classes.ts, packages/core/src/service/plugin/default.tsx, packages/core/src/service/plugin/index.ts, packages/core/src/service/plugin/missing.tsx, packages/core/src/types/editable.ts, packages/plugins/content/divider/src/createPlugin.tsx, packages/plugins/content/html5-video/src/createPlugin.tsx, packages/plugins/content/image/src/createPlugin.tsx, packages/plugins/content/slate/src/index.tsx, packages/plugins/content/spacer/src/createPlugin.tsx, packages/plugins/content/video/src/createPlugin.tsx, packages/plugins/createPluginMaterialUi/src/createContentPlugin.tsx, packages/plugins/layout/background/src/createPlugin.tsx, packages/plugins/layout/background/src/types/settings.ts, packages/ui/src/Toolbar/index.tsx
createInitialChildren on layoutplugins now can return a more simple
definition: an Array of Array of Cells, where a cell is in its simplest form an object:
```
{
content: {plugin: yourContentPlugin}
}
```
or another layout plugin:
```
{
layout: {plugin: yourLayoutPlugin}
}
```
=> feat: easier createInitialChildren for layout plugins

packages/plugins/content/video/package.json, packages/plugins/content/video/src/Renderer/VideoHtmlRenderer.tsx, packages/plugins/content/video/yarn.lock
upgrades react-player to latest version and lazy loads it, because the player lib is quite big
=> feat: upgrade video plugin

packages/core/tsconfig-es.json, packages/plugins/content/divider/tsconfig-es.json, packages/plugins/content/html5-video/tsconfig-es.json, packages/plugins/content/image/tsconfig-es.json, packages/plugins/content/native/tsconfig-es.json, packages/plugins/content/slate/tsconfig-es.json, packages/plugins/content/spacer/tsconfig-es.json, packages/plugins/content/video/tsconfig-es.json, packages/plugins/createPluginMaterialUi/tsconfig-es.json, packages/plugins/layout/background/tsconfig-es.json, packages/renderer/tsconfig-es.json, packages/ui/tsconfig-es.json
ES target was transpiling with es6 features (like `const` and `=>`). This PR keeps the `import`s and `export`s, but transpile to es5 code (`var` and `function`)
=> Don't use target es6 in es transpile to support IE11

examples/src/customLayoutPluginWithInitialState.tsx, examples/src/index.tsx, packages/core/src/actions/cell/core.ts, packages/core/src/actions/cell/insert.ts, packages/core/src/components/Cell/index.css, packages/core/src/components/Cell/index.tsx, packages/core/src/reducer/editable/__tests__/index.test.ts, packages/core/src/reducer/editable/tree.ts, packages/core/src/selector/index.ts, packages/core/src/service/plugin/index.ts, packages/core/src/service/plugin/missing.tsx, packages/core/src/types/editable.ts, packages/plugins/content/html5-video/src/Controls/Html5VideoDefaultControls.tsx, packages/plugins/content/image/src/Controls/ImageDefaultControls.tsx, packages/plugins/content/slate/src/Controls/index.tsx, packages/plugins/content/slate/src/serialization/index.tsx, packages/plugins/content/slate/src/types/initialSlateState.ts, packages/plugins/content/slate/src/utils/transformInitialSlateState.ts, packages/plugins/content/spacer/src/Controls/SpacerDefaultControls.tsx, packages/plugins/content/video/src/Controls/VideoDefaultControls.tsx, packages/plugins/createPluginMaterialUi/src/Controls/index.tsx, packages/plugins/layout/background/src/Controls/BackgroundDefaultControls.tsx, packages/renderer/src/index.tsx, packages/ui/src/BottomToolbar/index.tsx, packages/ui/src/DraftSwitch/index.tsx, packages/ui/src/DuplicateButton/index.tsx
_this PR is based on my previous PR: https://github.com/react-page/react-page/pull/744_
The bottom toolbar when selecting a cell now has new features:
- you can hide and show cells, setting them into a "draft" mode. These cells are only visible while in edit mode, but slightly transparent. They are not visible when rendered with readOnly/htmlRenderer
- a new clone button duplicates a cell. This works with layout plugins too! The new element will always inserted the cloned element.
- The title-bar with these actions has been moved below the rest of the toolbar. This is because i added these actions to the slate plugin as well and it looked better when the normal slate toolbar is next to the content.
The clone action was easy to do in the end, but it was not obvious how to do it. The action …
=> Feat: new toolbar actions: clone and hide

README.md
Following [discussion](https://github.com/react-page/react-page/issues/696#issuecomment-557559899) on #696 it seems that the URL in `README.md` should match the correct URL for the slack channel.
Only the readme was adjusted and so no tests were executed, and no functionality should have changed due to the changes.
No open issues are addressed by this.
=> correct link to slack in README.md

packages/core/src/components/DragDropProvider/index.tsx, packages/core/src/components/Editable/index.tsx, packages/core/src/index.ts, packages/editor/src/editor/EditableEditor.tsx, packages/editor/src/editor/index.tsx, packages/ui/src/EditorUI/index.tsx, packages/ui/src/Provider/index.tsx, packages/ui/src/index.tsx
You can now  customize the drag n drop backend from react-dnd. See https://react-dnd.github.io/react-dnd/docs/overview#backends for more information
example 
```
import Editor from '@react-page/editor';
import TouchBackend from 'react-dnd-touch-backend-cjs'
// ...
<Editor dndBackend={TouchBackend} />
```
or if you use the older Editable / EditorUI pair:
```
import EditorUi from '@react-page/ui';
import Editable from '@react-page/core';
import TouchBackend from 'react-dnd-touch-backend-cjs'
// ...
<Editable dndBackend={TouchBackend} /> 
// ...
<EditorUi dndBackend={TouchBackend} />
```
fixes https://github.com/react-page/react-page/issues/761
@PeterKottas can you test it a little?
=> feat: allow to pass react-dnd-backend

examples/src/customLayoutPluginWithInitialState.tsx, examples/src/slate.tsx, package.json, packages/plugins/content/slate/src/index.tsx, packages/plugins/content/slate/src/pluginFactories/createComponentPlugin.tsx, packages/plugins/content/slate/src/pluginFactories/createDataPlugin.tsx, packages/plugins/content/slate/src/pluginFactories/createListIndentionPlugin.tsx, packages/plugins/content/slate/src/pluginFactories/createListPlugin.tsx, packages/plugins/content/slate/src/pluginFactories/createSimpleHtmlBlockPlugin.tsx, packages/plugins/content/slate/src/plugins/code/index.tsx, packages/plugins/content/slate/src/types/SlatePlugin.ts, packages/plugins/content/slate/src/types/slatePluginDefinitions.ts, packages/plugins/content/slate/src/utils/makeSlatePluginsFromDef.ts, packages/plugins/content/slate/src/utils/transformInitialSlateState.ts, yarn.lock
feat: slate plugins can now be customized multiple times (calling it with a customize function)
feat: the slate plugin itself now defers the type of plugins and passes it to createInitialSlateState. This makes it easy to autocomplete you through all available plugins! even if you customize them:
```
import slate from '@react-page/plugins-slate';
const myCustomizedSlate = slate(def => ({
...def,
name: def.name + '/custom', // give it some other name
plugins: {
customStuff: {
myCustomSlatePlugin,
},
headings: {
h1: def.plugins.headings.h1,
h2: def.plugins.headings.h2,
},
paragraphs: def.plugins.paragraphs,
emphasize: def.plugins.emphasize,
},
}));
```
later in a layout plugin:
```
state: myCustomizedSlate.createInitialSlateState(({ plugins }) => ({
children: [
{
plugin: plugins.headings.h1, …
```
=> feat: small slate type improvements

packages/plugins/content/slate/src/Controls/ConditionalWrapper.tsx, packages/plugins/content/slate/src/Controls/ToolbarButton.tsx
Create a ConditionalWrapper component to only render Tooltip if button is active. 
Create a new component, to avoid material ui messge in disactive slate buttons:
```
Material-UI: you are providing a disabled `button` child to the Tooltip component.
A disabled element does not fire events.
Tooltip needs to listen to the child element's events to display the title.
Add a simple wrapper element, such as a `span`.
```
Only render tooltip if button is active.
=> [Fix] Only render tooltip in active buttons

examples/pages/examples/cellSpacing.tsx, examples/plugins/customLayoutPluginWithCellSpacing.tsx, examples/sampleContents/cellSpacing.tsx, packages/editor/src/core/Provider/index.tsx, packages/editor/src/core/components/Cell/Droppable/index.tsx, packages/editor/src/core/components/Cell/Inner/index.tsx, packages/editor/src/core/components/Cell/NoopProvider.tsx, packages/editor/src/core/components/Cell/PluginComponent/index.tsx, packages/editor/src/core/components/Cell/index.tsx, packages/editor/src/core/components/Editable/Inner/index.tsx, packages/editor/src/core/components/Row/ResizableRowCell.tsx, packages/editor/src/core/components/Row/index.css, packages/editor/src/core/components/Row/index.tsx, packages/editor/src/core/components/hooks/options.ts, packages/editor/src/core/components/hooks/options.tsx, packages/editor/src/core/types/node.ts, packages/editor/src/core/types/plugins.ts, packages/editor/src/core/utils/getCellSpacing.ts, packages/editor/src/editor/EditableEditor.tsx, packages/editor/src/editor/Editor.tsx, packages/editor/src/renderer/HTMLRenderer.tsx, packages/editor/src/renderer/__tests__/index.test.tsx, packages/plugins/layout/background/src/index.css
Add `cellSpacing` prop to the Editor where they can specify the sizes of grid gutters (vertical and horizontal).
#918
See examples/pages/examples/cellSpacing.tsx for the demonstration of the new functionality.
The main layout change is the split of .react-page-cell into two divs. The outer div gets all the flexgrid classes, inline classes (floats) and it's the div that gets all the paddings that constitute the gutters. The inner div retains all the rest of the classes and is the div that gets highlighted when a cell is selected.
Horizontal padding compensation is done by applying a negative margin to the .react-page-row class.
Vertical compensation is only needed for
- nested grids (layout plugins) and is applies to the new div that encloses the plugin's children (excluding the InsertNew …
=> fet(ui): cell spacing

packages/editor/src/core/components/Cell/Inner/index.tsx, packages/editor/src/core/components/Cell/InsertNew.tsx, packages/editor/src/core/components/Cell/index.tsx, packages/editor/src/core/components/Row/ResizableRowCell.tsx, packages/editor/src/core/components/Row/index.tsx
Allow clicks on layout plugin body to bubble up and be caught by the focusing logic.
Prevent blurAll when clicking on resize handle or when done resizing.
Stop propagation in their respective elements.
Handle phantom onClick for "react-page-row" separately -- that event is being fired when resizing stops.
Remove blurAll from the row (it was hit by the phantom onClick).
#945
=> bug(ui): trouble focusing the Background plugin

examples/package.json, packages/editor/package.json, packages/plugins/content/divider/package.json, packages/plugins/content/html5-video/package.json, packages/plugins/content/image/package.json, packages/plugins/content/slate/package.json, packages/plugins/content/spacer/package.json, packages/plugins/content/video/package.json, packages/plugins/createPluginMaterialUi/package.json, packages/plugins/layout/background/package.json, packages/react-admin/package.json
this is because react-dnd requires react 16.14 as min version. It should be usually safe to upgrade react to 16.14 or even 17.
fixes https://github.com/react-page/react-page/issues/961
=> fix: react version below 16.14. does no longer work

packages/editor/src/core/components/Cell/Draggable/index.css, packages/editor/src/core/components/Cell/Draggable/index.tsx, packages/editor/src/core/components/Cell/Handle/index.tsx
Fixes a problem with background plugins not responding to dragging in layout mode.
Also adds styles for highlighting a cell that is dragged by the cell handle.
Closes #962
=> fix/962: restore background dragging + dragging by handle styles

packages/editor/src/core/components/Cell/index.tsx
Signed-off-by: Peter Kottas <petokottas@gmail.com>
Removed extra stopPropagation on the cell in edit mode that's causing the BottomToolbar to mute clicks when listening for it via document.addEventListener
=> Fix: BottomToolbar stop propagation

packages/editor/src/core/actions/cell/insert.ts, packages/editor/src/core/components/hooks/nodeActions.ts
At some point, the "focus after duplicate" functionality got broken. I suspect it's because now we recreate all ids so the check that was previously there for moving things doesn't work (the id is already created once we go to that check). I've added a new option that defaults to current (broken) functionality.
=> Fix: Cell didn't focus after duplicate

packages/editor/src/core/components/Cell/Inner/index.tsx, packages/editor/src/core/components/Cell/InsertNew.tsx, packages/editor/src/core/components/Editable/Inner/index.tsx, packages/editor/src/core/types/components.ts
Feat: You can now replace the default InsertNew component via Components prop.
Feat: The InserNew component now gets children ids as a prop.
=> Feat: Added insert new to components

packages/editor/src/core/components/hooks/nodeActions.ts
fixes https://github.com/react-page/react-page/issues/1012
@PeterKottas that uses your new focusAfter option
=> fix: insert new does not focus cell

packages/editor/src/core/components/Cell/Droppable/index.tsx
fixes https://github.com/react-page/react-page/issues/1000
the bug arises from a confusion in the code:
if a cell is dropped, we have the `hoverTarget`, which is NOT the parent row or cell, but the new sibling.
So if you want to find out what is allowed next to that sibling, we have to look at the parent of the sibling, but the previous implementation used that node instead. If that node defined some custom cellplugins, this would lead to the bug described
=> fix: drag & drop in nested plugins behave wrong

examples/pages/readonly-bare.tsx, packages/editor/src/core/types/plugins.ts, packages/editor/src/renderer/HTMLRenderer.tsx, packages/plugins/content/slate/package.json, packages/plugins/content/slate/src/components/ReadOnlySlate.tsx, packages/plugins/content/slate/src/components/renderHooks.tsx, packages/plugins/content/slate/src/index.tsx, packages/plugins/content/slate/yarn.lock
this reduces bundle size (about 25kb gzipped) and probably render time (not measured yet) and unclutters the dom a bit.
it also introduces a new property `disableProviderInReadOnly` that will not render the provider in readonly mode.
As a matter of fact, slate is the only plugin we provide that uses a provider. It was necessary to also render the Provider in readonly mode,
but that is no longer true. We might deprecate that in the futur or make disableProviderInReadOnly the default.
BREAKING CHANGE: dom in readonly mode is slightly different
the resulting dom in readonly mode differ a bit from previous versions. (less elements)
This had no impact at all in the example project, but depending on your application
you might need to adjust styling. That is why this is released as a breaking …
=> feat(slate): slate uses now a custom static renderer in readonly mode

packages/editor/src/core/defaultOptions.ts, packages/editor/src/core/types/options.ts, packages/editor/src/ui/Sidebar/index.tsx
We can add custom option in the sidebar.
The purpose in my case is to add a save button
I didn't add documentation yet, I'm waiting to have an agreement of my feature before adding it
=> feat(sidebar): can add custom options in sidebar

examples/pages/examples/sidebarPosition.tsx, packages/editor/src/core/defaultOptions.ts, packages/editor/src/core/types/options.ts, packages/editor/src/editor/StickyWrapper.tsx, packages/editor/src/ui/EditorUI/index.tsx, packages/editor/src/ui/Sidebar/index.tsx
feat: new sidebar position options
- rightAbsolute: the default, fixed to the right of the screen
- rightRelative: immediatly right to the content
- leftRelative: immediatly left to the content
possible, but currently not implemented fully:
- leftAbsolute: left on the screen
=> feat: new sidebar position options

packages/plugins/content/image/src/Controls/ImageControls.tsx
change property of open in new window checkbox element of the image
plugin from 'value' to 'checked' so that it displays the correct state
of the openInNewWindow property
fixes issue #1140  Image plugin: "Open link in new window checkbox" is always unchecked
Change property of the checkbox element 'open in new window' in image plugin
following the controlled checkbox documentation of Material UI: https://v4.mui.com/api/checkbox/
`Closes #1140`
=> fix(image-plugin): fix image plugin open in new window checkbox state

packages/plugins/content/slate/src/pluginFactories/components/UniformsControls.tsx
Uniform- auto form actions should not be displayed when schema is null.
Refer #1175
Autoforms in plugins-slate shows autoform with cancel and ok button.
if schema is null auto-form should not be rendered
plugins-slate plugins wont render a auto from if schema of uniform control is null
- [x ] Lint and unit tests pass locally with my changes
=> fix(Autoform):Disable actions if schema null

packages/editor/src/ui/uniform-mui/ListDelField.tsx, packages/editor/src/ui/uniform-mui/ListField.tsx, packages/editor/src/ui/uniform-mui/ListItemField.tsx, packages/editor/src/ui/uniform-mui/ListSortField.tsx
Add the ability to reorder ListItemField items complementary to the ListDelField
addition of ListSortField, two buttons, with similar logic of ListDelField button that helps user change the order of the items on the list.
On the left side of the ListItemField component, as the delete button is on the right, so to prevent unintended deletions, addition of two buttons that allow a user to reorder the items on the list, either push the item up (if the item not already the first) and down (if the item is not already at the bottom)
=> feat: add reorder ability to ListItemField

packages/editor/src/core/components/hooks/node.ts, packages/plugins/content/slate/src/components/SlateProvider.tsx
fixes a rather nasty bug that was introduced recently.
This also finally simplify the complicated `useDebouncedCellData`-hook.
i _hope_ that this does not introduce a new problem, but it looks good so far
=> fix: changing language might override text in other language in slate
